// "use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Sections/Footer";
import getCurrentUser from "@/actions/get-current-user";
import { Toaster } from "@/components/ui/sonner";
import Hydration from "@/components/ui/Hydration";
import { ShoppingCartProvider } from "@/context/ShoppingCartContext";
import getCartQuantity from "@/actions/get-cart-quantity";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const currentUser = await getCurrentUser();
  // console.log(currentUser);

  const itemQuantity = await getCartQuantity();
  console.log(itemQuantity);

  return (
    <html lang="en">
      <body className={` ${inter.className} bg-stone-950 relative `}>
        <Toaster position="bottom-right" />
        {/* <ShoppingCartProvider> */}

        <div className="overflow-x-hidden">{children}</div>
        {/* </ShoppingCartProvider> */}
        <Hydration>
          <section className="sm:px-16 px-8 sm:py-12 py-8 bg-neutral-950">
            <Footer />
          </section>
        </Hydration>
      </body>
    </html>
  );
}
