import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Sections/Footer";
import getCurrentUser from "@/actions/get-current-user";
import { Toaster } from "@/components/ui/sonner";
import Hydration from "@/components/ui/Hydration";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const currentUser = await getCurrentUser();
  // console.log(currentUser);

  return (
    <html lang="en">
      <body className={` ${inter.className} bg-stone-950 relative `}>
        <Toaster position="bottom-right" />
        <Hydration>
          <Header />
        </Hydration>
        <div className="overflow-x-hidden">{children}</div>
        <Hydration>
          <section className="sm:px-16 px-8 sm:py-12 py-8 bg-neutral-950">
            <Footer />
          </section>
        </Hydration>
      </body>
    </html>
  );
}
