import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Sections/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${inter.className} bg-stone-800 relative `}>
        <Header />
        <div className="overflow-x-hidden">{children}</div>
        <section className="sm:px-16 px-8 sm:py-12 py-8 bg-neutral-950">
          <Footer />
        </section>
      </body>
    </html>
  );
}
