"use client";
import Hydration from "@/components/ui/Hydration";
import Header from "@/components/Header";
// import { Inter } from "next/font/google";
// import "./globals.css";
import { ShoppingCartProvider } from "@/context/ShoppingCartContext";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const currentUser = await getCurrentUser();
  // console.log(currentUser);

  return (
    <ShoppingCartProvider>
      <Hydration>
        <Header />
      </Hydration>
      {children}
    </ShoppingCartProvider>
  );
}
